#!/bin/sh
set -e

source /usr/local/bin/docker-varnish-entrypoint-prepopulate-conf.sh

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnishd \
	    -F \
	    -f /etc/varnish/default.vcl \
	    -a http=:80,HTTP \
	    -a proxy=:8443,PROXY \
	    -p feature=+http2 \
	    -p http_max_hdr=512 \
	    -p http_req_hdr_len=16384 \
     	    -p http_resp_hdr_len=16384 \
	    -p workspace_backend=2M \
 	    -p workspace_client=2M \
	    -s malloc,$VARNISH_SIZE \
	    "$@"
fi

exec "$@"
