name: Create and publish Magento Docker image

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      NEWRELIC_KEY: ${{ secrets.NEWRELIC_KEY }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: magento/php7.4
            image: ghcr.io/hsf-digital-team/magento-php7.4-base
          - dockerfile: magento/php8.1
            image: ghcr.io/hsf-digital-team/magento-php8.1-base
          - dockerfile: magento/php8.2
            image: ghcr.io/hsf-digital-team/magento-php8.2-base

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "NEWRELIC_KEY=${{ secrets.NEWRELIC_KEY }}"   
